name: Deploy Image to ECR
on:
  workflow_dispatch:
  # push:
  #   branches: [main]

permissions:
  contents: read
  id-token: write
# the above permissions are needed for the GitHub token to authenticate with AWS using OIDC and get temporary credentials for deployment

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: "arn:aws:iam::687848809549:role/oidc-dev"
          aws-region: eu-west-1
          role-session-name: OIDC-Session

      - name: Verify IAM Role Assumption
        run: aws sts get-caller-identity

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build, tag, and push the image to Amazon ECR
#         id: build-image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
#           IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
#         run: |
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

# # the above workflow will build a Docker image from the root of the repository, tag it with the ECR registry and repository name, and push it to ECR. 
# # The image tag is generated using the commit hash and a timestamp to ensure uniqueness.

#       - name: Deploy with Terraform
#         run: |
#           terraform init
#           terraform apply -auto-approve